Repository Stre4K/pykemon, pull requests merged in 2025-05, with the labels that each got.

#22 Update README.md with new starting guide
  README.md
Labels: documentation

#24 23 improve multiplayer handling
  README.md
  src/client.py
  src/client/__init__.py
  src/client/client.py
  src/core/__init__.py
  src/core/pykemon.py
  src/core/spell.py
  src/load_spells.py
  src/main.py
  src/server.py
  src/server/__init__.py
  src/server/server.py
  src/spell.py
  src/start.py
  src/utils/__init__.py
  src/utils/utils.py
Labels: enhancement

#37 Fix import path/package
  src/client/client.py
  src/core/pykemon.py
  src/server/server.py
  src/utils/utils.py
Labels: bug

#40 39 update readmemd with current information
  README.md
Labels: documentation

#42 Updated input variable name for cast_spell
  src/core/pykemon.py
Labels: documentation, enhancement

#45 Fix issue #38
  src/main.py
Labels: enhancement
